### ISSUE TITLE
Where's the report

### ISSUE THREAD

**Issue by fray1014** [russwong89/sharpness_detection_autofocus#3]
As you wrote in the readme, algorithmic details can be found in the report, "Development of a Contrast-Based Autofocus Algorithm using Numerical Methods". However, I couldn't find this report anywhere.
Could you provide the link of the report?

**Comment by russwong89** [comment]
Hello!

Unfortunately we are not able to provide the report as it was used as a graded assignment. This repository is not being actively maintained and was merely used for a project submission in a university course.
